### ISSUE TITLE
Print rule name on failure

### ISSUE THREAD

**Issue by cowwoc** [adametry/gulp-eslint#237]
When I get an ESLint error I get the following output:

```
Message:
    Unexpected console statement.
Details:
    fileName: SomePath\Terminal.js
    lineNumber: 79
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false
```

I would like to know which eslint rule name corresponds to "Unexpected console statement". I could Google the error message and track it back to the source, but ideally the output should provide the rule name directly,
